### ISSUE TITLE
Como rodar o projeto local?

### ISSUE THREAD

**Issue by clautercarlos** [ops-org/operacao-politica-supervisionada#47]
Há algum guia pra rodar a api localmente e carregar dados para o frontend?

**Comment by RafaelEstevamReis** [comment]
Ainda não
Praticamente tudo está na cabeça do @VanderleiDenir e alguns poucos que conheciam a estrutura não estão mais ativos

Eu comecei a fuçar no projeto no fim de dezembro e senti a mesma falta

O Vanderlei está me ajudando à implementar um "Importador" [Importar-Notas](https://github.com/ops-org/operacao-politica-supervisionada/tree/Importar-Notas)
Posso documentar essa parte e vamos construindo um guia mais completo

**Comment by RafaelEstevamReis** [comment]
@clautercarlos, fiz a adição de documentação inicial
https://github.com/ops-org/operacao-politica-supervisionada/pull/48

Esse PR adicionou o guia de contribuição
https://github.com/ops-org/operacao-politica-supervisionada/blob/master/CONTRIBUTING.md

Dá uma seguida nos passos e qualquer dúvida me chama que vamos melhorando o documento

**Comment by clautercarlos** [comment]
Muito bom! Obrigado!
