### ISSUE TITLE
É permitido usar a API do OPS ?

### ISSUE THREAD

**Issue by cassioscabral** [ops-org/operacao-politica-supervisionada#9]
fazer request de outro site a  API como um "GET http://ops.net.br/api/deputado/idDeputado" ?

estou participando de um hackathon(Hack Fest 2017) na PB contra a corrupção e pretendo agregar informações de dados públicos já processados por outras pessoas para exibir em uma única página. 

Podemos adicionar o logo e link para o site da OPS

**Comment by VanderleiDenir** [comment]
Embora não tenhamos uma documentação da API e acredito que ela não possa ser chamada diretamente pelo cliente (CORS não habilitado), você pode utilizar sem problemas.

**Comment by cassioscabral** [comment]
Obrigado @VanderleiDenir, usamos ela durante o evento para testar o MVP mas vamos priorizar coletar os dados que conseguirmos para não sobrecarregar a API. Ficamos entre as 10 equipes ganhadoras.

**Comment by VanderleiDenir** [comment]
Parabéns à equipe.
Acredito que não iremos ter problemas com sobrecarga por que cada requisição feita fica em cache de 12h. Com isso evitamos a sobrecarga ao banco para as requisições idênticas já processadas.
Qualquer duvida ou sugestão quanto a API ou mesmo a CEAP pode entrar em contato.
